/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.Compras;

import Reportes.fac_comreport;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.Det_factura_com;
import Models.Det_orden_com;
import Models.Factura_com;
import Models.Libroiva;
import Models.Orden_com;
import Models.Producto;
import Models.Proveedor;
import Models.Usuario;
import Models.datos_login;
import DAO.Det_factura_com_daoimpl;
import DAO.Factura_com_daoimpl;
import DAO.LibroivaDaoImpl;
import DAO.LoginDaoImpl;
import DAO.Orden_com_daoimpl;
import DAO.Producto_daoimpl;
import DAO.ProveedorDaoImpl;
import DAO.UsuarioDaoImpl;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.util.HibernateUtil;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author Ramc
 */
public class Facturaciones extends javax.swing.JDialog {

    /**
     * Creates new form Presupuesto
     */
    public Facturaciones(java.awt.Frame parent, boolean modal) throws UnknownHostException {
        super(parent, modal);
        initComponents();
        arranque();
        setLocationRelativeTo(null);
    }
    Session st = HibernateUtil.getSessionFactory().openSession();
    private final LoginDaoImpl logdao= new LoginDaoImpl(st);
    private final Producto_daoimpl pdao = new Producto_daoimpl(st);
    private final ProveedorDaoImpl cdao = new ProveedorDaoImpl(st);
    private final UsuarioDaoImpl udao = new UsuarioDaoImpl(st);
    private final LibroivaDaoImpl lidao = new LibroivaDaoImpl(st);
    private final Orden_com_daoimpl ordao = new Orden_com_daoimpl(st);
    private final Factura_com_daoimpl facdao = new Factura_com_daoimpl(st);
    private final Det_factura_com_daoimpl dtdao = new Det_factura_com_daoimpl(st);
    private DefaultTableModel modelpr,modelclie, modelpres, model, modelpe, modelli;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar_Pedido = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaped = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        agregarped = new javax.swing.JButton();
        cancelarped = new javax.swing.JButton();
        fechaped = new javax.swing.JFormattedTextField();
        buscarped = new javax.swing.JButton();
        Buscar_Presupuesto = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablapres = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        agregarpres = new javax.swing.JButton();
        cancelarpres = new javax.swing.JButton();
        fechapres = new javax.swing.JFormattedTextField();
        buscarpres = new javax.swing.JButton();
        libroivam = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablib = new javax.swing.JTable();
        combolib = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        botbuscar = new javax.swing.JButton();
        txtnro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtrazonsocial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnroproveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnroproducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        botnuevo = new javax.swing.JButton();
        botguardar = new javax.swing.JButton();
        botanular = new javax.swing.JButton();
        botquitar = new javax.swing.JButton();
        botcancelar = new javax.swing.JButton();
        botsalir = new javax.swing.JButton();

        Buscar_Pedido.setSize(new java.awt.Dimension(650, 750));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Buscar Orden de Compra");

        tablaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NRO", "FECHA"
            }
        ));
        jScrollPane5.setViewportView(tablaped);

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarped.setText("Agregar");
        agregarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpedMouseClicked(evt);
            }
        });
        agregarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarpedActionPerformed(evt);
            }
        });

        cancelarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarped.setText("Cancelar");
        cancelarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpedActionPerformed(evt);
            }
        });

        try {
            fechaped.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaped.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarped.setText("Buscar Fecha");
        buscarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechaped, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarped, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarped, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarped, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarped, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaped, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PedidoLayout = new javax.swing.GroupLayout(Buscar_Pedido.getContentPane());
        Buscar_Pedido.getContentPane().setLayout(Buscar_PedidoLayout);
        Buscar_PedidoLayout.setHorizontalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        Buscar_PedidoLayout.setVerticalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        Buscar_Presupuesto.setSize(new java.awt.Dimension(650, 750));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Buscar Factura");

        tablapres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablapres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NRO", "FECHA", "PROVEEDOR"
            }
        ));
        jScrollPane3.setViewportView(tablapres);

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarpres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarpres.setText("Agregar");
        agregarpres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarpresMouseEntered(evt);
            }
        });
        agregarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarpresActionPerformed(evt);
            }
        });

        cancelarpres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarpres.setText("Cancelar");
        cancelarpres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarpresMouseClicked(evt);
            }
        });
        cancelarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpresActionPerformed(evt);
            }
        });

        try {
            fechapres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechapres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechapres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarpres.setText("Buscar Fecha");
        buscarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechapres, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarpres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarpres, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarpres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechapres, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PresupuestoLayout = new javax.swing.GroupLayout(Buscar_Presupuesto.getContentPane());
        Buscar_Presupuesto.getContentPane().setLayout(Buscar_PresupuestoLayout);
        Buscar_PresupuestoLayout.setHorizontalGroup(
            Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        Buscar_PresupuestoLayout.setVerticalGroup(
            Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        libroivam.setSize(new java.awt.Dimension(850, 600));

        tablib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "FECHA", "IVA 10%", "IVA 5%", "TIPO", "FACTURA", "NOTA DE CREDITO", "TIMBRADO"
            }
        ));
        jScrollPane2.setViewportView(tablib);

        combolib.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODO", "Credito", "Debito" }));

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout libroivamLayout = new javax.swing.GroupLayout(libroivam.getContentPane());
        libroivam.getContentPane().setLayout(libroivamLayout);
        libroivamLayout.setHorizontalGroup(
            libroivamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libroivamLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(libroivamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combolib, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(45, 45, 45))
        );
        libroivamLayout.setVerticalGroup(
            libroivamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libroivamLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(libroivamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combolib)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("FACTURACIONES");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CANTIDAD", "CODIGO", "DESCRIPCION", "PRECIO", "TOTAL"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel15.setText("TOTAL");

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        botbuscar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscar.setText("Buscar Factura");
        botbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarActionPerformed(evt);
            }
        });

        txtnro.setEditable(false);
        txtnro.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("Nro de Factura");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel11.setText("Fecha");

        txtfecha.setEditable(false);
        try {
            txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfecha.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("Usuario");

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        txtrazonsocial.setEditable(false);
        txtrazonsocial.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel8.setText("Razon Social");

        txtruc.setEditable(false);
        txtruc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrucActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel7.setText("RUC");

        txtnroproveedor.setEditable(false);
        txtnroproveedor.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel6.setText("Nro");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("Nro");

        txtnroproducto.setEditable(false);
        txtnroproducto.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setText("Descripcion");

        txtdescripcion.setEditable(false);
        txtdescripcion.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        botnuevo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botnuevo.setText("Nuevo");
        botnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnuevoActionPerformed(evt);
            }
        });

        botguardar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botguardar.setText("Guardar");
        botguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botguardarActionPerformed(evt);
            }
        });

        botanular.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botanular.setText("Anular");
        botanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botanularActionPerformed(evt);
            }
        });

        botquitar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botquitar.setText("Quitar");
        botquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botquitarActionPerformed(evt);
            }
        });

        botcancelar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botcancelar.setText("Cancelar");
        botcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botcancelarActionPerformed(evt);
            }
        });

        botsalir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botsalir.setText("Salir");
        botsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnroproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(70, 70, 70)
                                            .addComponent(txtrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(txtnro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(113, 113, 113)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(txtnroproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(70, 70, 70)
                                            .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(botguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(botanular, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(493, 493, 493)
                                    .addComponent(botquitar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(botcancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnroproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnroproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(botnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(botguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botanular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botquitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void agregarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpedMouseClicked

    }//GEN-LAST:event_agregarpedMouseClicked

    private void agregarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarpedActionPerformed
        retornarFactura();// TODO add your handling code here:
    }//GEN-LAST:event_agregarpedActionPerformed

    private void cancelarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpedActionPerformed
        Buscar_Pedido.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpedActionPerformed

    private void buscarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpedActionPerformed
        tabpedidos();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpedActionPerformed

    private void agregarpresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpresMouseClicked

    }//GEN-LAST:event_agregarpresMouseClicked

    private void agregarpresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarpresMouseEntered

    private void agregarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarpresActionPerformed
        retornarPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_agregarpresActionPerformed

    private void cancelarpresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarpresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarpresMouseClicked

    private void cancelarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpresActionPerformed
        Buscar_Presupuesto.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpresActionPerformed

    private void buscarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpresActionPerformed
        tablaPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpresActionPerformed

    private void botbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarActionPerformed
        buscarPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_botbuscarActionPerformed

    private void botnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnuevoActionPerformed
        try {
            nuevo();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Facturaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botnuevoActionPerformed

    private void botguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botguardarActionPerformed
        try {
            guardar();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Facturaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Facturaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botguardarActionPerformed

    private void botanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botanularActionPerformed
        anular();        // TODO add your handling code here:
    }//GEN-LAST:event_botanularActionPerformed

    private void botquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botquitarActionPerformed
        removerProducto();        // TODO add your handling code here:
    }//GEN-LAST:event_botquitarActionPerformed

    private void botcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botcancelarActionPerformed
        try {
            arranque();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Facturaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botcancelarActionPerformed

    private void botsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botsalirActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        selecTable(); // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tablibros();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        libroivam.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Facturaciones dialog = null;
                try {
                    dialog = new Facturaciones(new javax.swing.JFrame(), true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Facturaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Buscar_Pedido;
    private javax.swing.JDialog Buscar_Presupuesto;
    private javax.swing.JButton agregarped;
    private javax.swing.JButton agregarpres;
    private javax.swing.JButton botanular;
    private javax.swing.JButton botbuscar;
    private javax.swing.JButton botcancelar;
    private javax.swing.JButton botguardar;
    private javax.swing.JButton botnuevo;
    private javax.swing.JButton botquitar;
    private javax.swing.JButton botsalir;
    private javax.swing.JButton buscarped;
    private javax.swing.JButton buscarpres;
    private javax.swing.JButton cancelarped;
    private javax.swing.JButton cancelarpres;
    private javax.swing.JComboBox<String> combolib;
    private javax.swing.JFormattedTextField fechaped;
    private javax.swing.JFormattedTextField fechapres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog libroivam;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaped;
    private javax.swing.JTable tablapres;
    private javax.swing.JTable tablib;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtnroproducto;
    private javax.swing.JTextField txtnroproveedor;
    private javax.swing.JTextField txtrazonsocial;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
    private Calendar f;
    private void arranque() throws UnknownHostException{
        txtnro.setText(null);
        txtestado.setText(null);
        txttimbrado.setEnabled(false);
        txtfechafac.setEnabled(false);
        txttotal.setText(null);
        txttotal10.setText(null);
        txttotal5.setText(null);
        combotipo.setEnabled(false);
        combotipo.setSelectedIndex(-1);
        txttimbrado.setText(null);
        txtfechafac.setText(null);
        txtnro.setEnabled(false);
        txtnroproducto.setText(null);
        f = (Calendar.getInstance());
        txtfecha.setText(retornarString(f));
        txtnroproveedor.setText(null);
        txtruc.setText(null);
        txtrazonsocial.setText(null);
        txtdescripcion.setText(null);
        botbuscar.setEnabled(true);
        botbuscarpedido.setEnabled(false);
        botquitar.setEnabled(false);
        botguardar.setEnabled(false);
        txtpedido.setText(null);
        txtusuariopedido.setText(null);
        txtfechapedido.setText(null);
        botanular.setEnabled(false);
        tabla.setEnabled(true);
        botnuevo.setEnabled(true);
        tableModel();
        retornarusuario();
    }
    
    private String hostname;
    private void retornarusuario() throws UnknownHostException{
        List<datos_login> list = logdao.list();
        InetAddress localHost = InetAddress.getLocalHost();
        hostname = localHost.getHostName();
        if(list!=null){
            for(datos_login u: list){
                if(u.getEstado().equals(true) && hostname.equals(u.getMaquina())){
                    txtusuario.setText(u.getUsuario().getNombre());
                }
            }
        }   
    }
    
    private String retornarString(Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private void tableModel(){
    tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
    tabla.getColumnModel().getColumn(1).setPreferredWidth(230);
    tabla.getColumnModel().getColumn(2).setPreferredWidth(130);
    tabla.getColumnModel().getColumn(3).setPreferredWidth(230);
    tabla.getColumnModel().getColumn(4).setPreferredWidth(130);
    model = (DefaultTableModel)tabla.getModel();
    model.setNumRows(0);
    }
    
    private void nuevo() throws UnknownHostException{
        f = (Calendar.getInstance());
        txtfecha.setText(retornarString(f));
        retornarusuario();
        tabla.setEnabled(true);
        combotipo.setEnabled(true);
        txttimbrado.setEnabled(true);
        txtfechafac.setEnabled(true);
        botbuscar.setEnabled(false);
        botnuevo.setEnabled(false);
        botbuscarpedido.setEnabled(true); 
        botguardar.setEnabled(true);
        id();
    }
    
    private void tabpedidos(){
        tablaped.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaped.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpe = (DefaultTableModel)tablaped.getModel();
        modelpe.setNumRows(0);
        List<Orden_com> list = ordao.list();
        for (Orden_com l : list){
            if(l.getEstado().equals("ACTIVO")){
               if(fechaped.getText().equals("  /  /    ")){
                    modelpe.addRow(new Object[]{
                    l.getId_ord(), retornarString(l.getFecha())
                    }); 
               }else{
                   if(fechaped.getText().equals(retornarString(l.getFecha()))){
                        modelpe.addRow(new Object[]{
                        l.getId_ord(), retornarString(l.getFecha())
                        }); 
                   }
               }
            }  
        }
    }
    
    private void buscarfactura(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabpedidos();
        Buscar_Pedido.setModal(true);
        Buscar_Pedido.setLocation(x,y);
        Buscar_Pedido.setLocationRelativeTo(null);
        Buscar_Pedido.setVisible(true);
    }
    
    private void retornarFactura(){
        if(tablaped.getRowCount() > 0){
            if(tablaped.getSelectedRow() != -1){
            Orden_com or = ordao.buscarPorId(Integer.parseInt(modelpe.getValueAt(tablaped.getSelectedRow(), 0).toString()));
            txtpedido.setText(String.valueOf(or.getId_ord()));
            txtfechapedido.setText(retornarString(or.getFecha()));
            txtusuariopedido.setText(String.valueOf(or.getId_us().getNombre()));
            txtnroproveedor.setText(String.valueOf(or.getId_prov().getId_prov()));
            txtruc.setText(String.valueOf(or.getId_prov().getRuc()));
            txtrazonsocial.setText(String.valueOf(or.getId_prov().getRazon_social()));
            List<Det_orden_com> dt =or.getDetalles();
            model.setNumRows(0);
            tabla.setEnabled(true);
            for (Det_orden_com p : dt) {
                model.addRow(new Object[]{
                    p.getCantidad(),  p.getId_prod().getId_prod(),  p.getId_prod().getDescripcion(),  p.getPrecio(),  (p.getCantidad() * p.getPrecio())
                });
            } 
            botnuevo.setEnabled(false);
            Buscar_Pedido.dispose();
            botbuscar.setEnabled(false);
             total();
            }
        }
    }
    
    private void tablaPresupuesto(){
        tablapres.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablapres.getColumnModel().getColumn(1).setPreferredWidth(180);
        tablapres.getColumnModel().getColumn(2).setPreferredWidth(180);
        modelpres = (DefaultTableModel)tablapres.getModel();
        modelpres.setNumRows(0);
        List<Factura_com> list = facdao.list();
        for (Factura_com l : list){
            
                if(fechapres.getText().equals("  /  /    ")){
                   modelpres.addRow(new Object[]{
                    l.getId_fac(),retornarString(l.getFecha()),l.getId_prov().getRazon_social()
                }); 
                }else{
                   if(fechapres.getText().equals(retornarString(l.getFecha()))){
                       modelpres.addRow(new Object[]{
                    l.getId_fac(), retornarString(l.getFecha()),l.getId_prov().getRazon_social()
                }); 
                   }
                }
            
        }
    }
     
     private void buscarPresupuesto(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tablaPresupuesto();
        Buscar_Presupuesto.setModal(true);
        Buscar_Presupuesto.setLocation(x,y);
        Buscar_Presupuesto.setLocationRelativeTo(null);
        Buscar_Presupuesto.setVisible(true);
    }
     
    private void retornarPresupuesto(){
        if(tablapres.getRowCount() > 0){
            if(tablapres.getSelectedRow() != -1){
            Factura_com pe = facdao.buscarPorId(Integer.parseInt(modelpres.getValueAt(tablapres.getSelectedRow(), 0).toString()));
            txtnro.setText(String.valueOf(pe.getId_fac()));
            txtfecha.setText(retornarString(pe.getFecha()));
            txtusuario.setText(String.valueOf(pe.getId_us().getNombre()));
            txtpedido.setText(String.valueOf(pe.getId_ord().getId_ord()));
            txtfechapedido.setText(String.valueOf(retornarString(pe.getId_ord().getFecha())));
            txtusuariopedido.setText(String.valueOf(pe.getId_ord().getId_us().getNombre()));
            txtnroproveedor.setText(String.valueOf(pe.getId_prov().getId_prov()));
            txtruc.setText(String.valueOf(pe.getId_prov().getRuc()));
            txtrazonsocial.setText(String.valueOf(pe.getId_prov().getRazon_social()));
            combotipo.setSelectedItem(pe.getTipo());
            txttimbrado.setText(pe.getTimbrado());
            txtfechafac.setText(pe.getFecha_fac());
            List<Det_factura_com> dt =pe.getDetalles();
            model.setNumRows(0);
            tabla.setEnabled(false);
            for (Det_factura_com p : dt) {
                model.addRow(new Object[]{
                    p.getCantidad(),p.getId_prod().getId_prod(),p.getId_prod().getDescripcion(),p.getPrecio(),(p.getCantidad() * p.getPrecio())
                });
            } 
            botnuevo.setEnabled(false);
            Buscar_Presupuesto.dispose();
            botbuscar.setEnabled(false);
            txtestado.setText(pe.getEstado());
            id = pe.getId_fac();

            if(pe.getEstado().equals("ACTIVO")){
                botanular.setEnabled(true);
            }else{
                botanular.setEnabled(false);
            }
             total();
            }
        }
    }
    
    
    private void total(){
        txttotal.setText(null);
        txttotal10.setText(null);
        txttotal5.setText(null);
        int tot=0;
        int tot10=0;
        int tot5=0;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            Producto pro = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
            if(pro.getIva().equals("10%")){
                tot10 = tot10 + (Integer.parseInt(model.getValueAt(i, 4).toString()));
            }else{
                tot5 = tot5 + (Integer.parseInt(model.getValueAt(i, 4).toString()));
            }
            tot= tot + (Integer.parseInt(model.getValueAt(i, 4).toString()));
            
        }
        tot10 = tot10 / 11;
        tot5 = tot5 /  11;
        txttotal.setText(String.valueOf(tot));
        txttotal10.setText(String.valueOf(tot10));
        txttotal5.setText(String.valueOf(tot5));
    }
    
    private void removerProducto(){
        if(tabla.getRowCount() > 0){
            if(tabla.getSelectedRow() != -1){
                model.removeRow(tabla.getSelectedRow());
            }
        }
        total();
    }
   
    private void guardar() throws UnknownHostException, JRException{
        if(tabla.getRowCount() > 0){
            if(!txtusuario.getText().isEmpty()){
                if(!txtruc.getText().isEmpty()){
                    if(!txtpedido.getText().isEmpty() && !txttimbrado.getText().isEmpty() && !txtfechafac.getText().isEmpty() && combotipo.getSelectedIndex() > -1){
                        if(JOptionPane.showConfirmDialog(null, "Desea guardar este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
                            Usuario us = udao.buscarPorNom(txtusuario.getText());
                            Proveedor prov = cdao.buscarPorId(Integer.parseInt(txtnroproveedor.getText()));
                            Orden_com ord = ordao.buscarPorId(Integer.parseInt(txtpedido.getText()));
                            String pag = "A PAGAR";
                            if(combotipo.getSelectedItem().equals("Contado")){
                                pag = "PAGADO";
                            }
                            Factura_com fac = new   Factura_com(txttimbrado.getText(),f,txtfechafac.getText(),combotipo.getSelectedItem().toString(),
                                                                Integer.parseInt(txttotal.getText()),Integer.parseInt(txttotal10.getText())
                                                                ,Integer.parseInt(txttotal5.getText()),"ACTIVO",pag,ord,prov,us);
                                for (int i = 0; i < tabla.getRowCount(); i++) {
                                    Det_factura_com dt= new Det_factura_com();
                                    dt.setCantidad(Integer.parseInt(model.getValueAt(i, 0).toString()));
                                    dt.setPrecio(Integer.parseInt(model.getValueAt(i, 3).toString()));
                                    Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
                                    dt.setId_prod(p);
                                    fac.getDetalles().add(dt);
                                    dt.setId_fac(fac);
                                    
                                    int stk = p.getStock();
                                    p.setStock(stk + Integer.parseInt(model.getValueAt(i, 0).toString()));
                                    pdao.actualizar(p);
                                    
                                }
                            facdao.guardar(fac);
                            JOptionPane.showMessageDialog(null, "Guardado correctamente");
                            ord.setEstado("REALIZADO");
                            ordao.actualizar(ord);
                            Libroiva li = new Libroiva(f, Integer.parseInt(txttotal10.getText()),Integer.parseInt(txttotal5.getText()),"debito", fac,null);
                            lidao.guardar(li);
                            imprimir();
                            arranque();
                        } 
                    }else{
                        JOptionPane.showMessageDialog(null, "Campos vacios");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Indique el cliente");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Inicie sesion");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Agregue un producto al la lista");
        }
        
        
    }
    
    private void anular(){
        if(JOptionPane.showConfirmDialog(null, "Desea anular este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
            if(!txtnro.getText().isEmpty()){
                Factura_com fac = facdao.buscarPorId(Integer.parseInt(txtnro.getText()));
                Orden_com or = ordao.buscarPorId(Integer.parseInt(txtpedido.getText()));
                if(fac.getEstado().equals("ACTIVO")){
                    for (int i = 0; i < tabla.getRowCount(); i++) {
                        Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
                        int stk = p.getStock();
                        p.setStock(stk - Integer.parseInt(model.getValueAt(i, 0).toString()));
                        pdao.actualizar(p);
                    }
                    Libroiva li = new Libroiva(f, Integer.parseInt(txttotal10.getText()),Integer.parseInt(txttotal5.getText()),"credito", fac,null);
                    lidao.guardar(li);
                    fac.setEstado("ANULADO");
                    botanular.setEnabled(false);
                    facdao.actualizar(fac);
                    or.setEstado("ACTIVO");
                    ordao.actualizar(or);
                    txtestado.setText("ANULADO");
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se puede anular");
                }
            }
        }
    }
    
    private void selecTable(){
        if(tabla.getRowCount()> 0){
            if(tabla.isEnabled()){
                if(tabla.getSelectedRow()> -1){
                   Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(tabla.getSelectedRow(),1).toString()));
                   txtnroproducto.setText(String.valueOf(p.getId_prod()));
                   txtdescripcion.setText(p.getDescripcion());
                   botquitar.setEnabled(true);
                }
            }
        }
    }
    
    private int id;
    private void id(){
       List<Factura_com> listvn=facdao.list();
       id=1;
       for(Factura_com ven: listvn){
           id=ven.getId_fac()+1;
       }
       txtnro.setText(String.valueOf(id));
    }
    
    private void imprimir() throws JRException{  
         try {
            Factura_com fc = facdao.buscarPorId(Integer.parseInt(txtnro.getText()));
            List fac=new ArrayList();
            List<Det_factura_com> list = fc.getDetalles(); 
            for(Det_factura_com dt: list){
                fac.add(new fac_comreport(String.valueOf(dt.getCantidad()),String.valueOf(dt.getId_prod().getId_prod()), dt.getId_prod().getDescripcion(),
                                            String.valueOf(dt.getPrecio()), String.valueOf((dt.getCantidad()* dt.getPrecio()))));
            }       
                JasperReport report  = (JasperReport)JRLoader.loadObject(ClassLoader.getSystemResource("Reportes/Factura.jasper"));
                Map<String, Object> parametro = new HashMap<String, Object>();
                parametro.put("nro",String.valueOf(fc.getId_fac()));
                parametro.put("timbrado", fc.getTimbrado());
                parametro.put("fecha", retornarString(fc.getFecha()));
                parametro.put("usser",fc.getId_us().getNombre());
                parametro.put("cliente", (fc.getId_prov().getRazon_social()));
                parametro.put("ruc", fc.getId_prov().getRuc());
                parametro.put("total",String.valueOf(fc.getTotal()));
                parametro.put("total5", String.valueOf(fc.getTotaliva5()));
                parametro.put("total10", String.valueOf(fc.getTotaliva10()));
                JasperPrint fillReport = JasperFillManager.fillReport(report, parametro ,new JRBeanCollectionDataSource(fac));
                JasperViewer jviewer = new JasperViewer(fillReport,false);
                    jviewer.setTitle("Factura de Ventas");
                    jviewer.setVisible(true);
                } catch (JRException e) {
                JOptionPane.showMessageDialog(null, "Error cargando reporte."+e);        
            } catch (HibernateException e) {
                JOptionPane.showMessageDialog(null, "Error cargando reporte."+e);
        }
        }
    
    
       private void tablibros(){
        tablib.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablib.getColumnModel().getColumn(1).setPreferredWidth(80);
        tablib.getColumnModel().getColumn(2).setPreferredWidth(80);
        tablib.getColumnModel().getColumn(3).setPreferredWidth(80);
        tablib.getColumnModel().getColumn(4).setPreferredWidth(80);
        tablib.getColumnModel().getColumn(5).setPreferredWidth(80);
        tablib.getColumnModel().getColumn(5).setPreferredWidth(80);
        modelli = (DefaultTableModel)tablib.getModel();
        modelli.setNumRows(0);
        List<Libroiva> list = lidao.list();
        for (Libroiva l : list){
            if(combolib.getSelectedItem().toString().equals("TODO")){
               if(l.getId_fac() == null){
                    modelli.addRow(new Object[]{
                    retornarString(l.getFecha()),l.getIva10(),l.getIva5(),l.getTipo(),null,l.getId_nc().getId_nc(),l.getId_nc().getTimbrado()
                    }); 
               }else{
                   modelli.addRow(new Object[]{
                    retornarString(l.getFecha()),l.getIva10(),l.getIva5(),l.getTipo(),l.getId_fac().getId_fac(),null,l.getId_fac().getTimbrado()
                    }); 
               }
            }else{ 
                if(combolib.getSelectedItem().toString().equals("Credito")){
                    if (l.getTipo().equals("credito")) {
                         if(l.getId_fac() == null){
                            modelli.addRow(new Object[]{
                            retornarString(l.getFecha()),l.getIva10(),l.getIva5(),l.getTipo(),null,l.getId_nc().getId_nc(),l.getId_nc().getTimbrado()
                            }); 
                        }else{
                            modelli.addRow(new Object[]{
                             retornarString(l.getFecha()),l.getIva10(),l.getIva5(),l.getTipo(),l.getId_fac().getId_fac(),null,l.getId_fac().getTimbrado()
                             }); 
                        }   
                    }
                }else{
                    if (combolib.getSelectedItem().toString().equals("Debito")) {
                        
                        if (l.getTipo().equals("debito")) {
                             if(l.getId_fac() == null){
                                modelli.addRow(new Object[]{
                                retornarString(l.getFecha()),l.getIva10(),l.getIva5(),l.getTipo(),null,l.getId_nc().getId_nc(),l.getId_nc().getTimbrado()
                                }); 
                            }else{
                                modelli.addRow(new Object[]{
                                 retornarString(l.getFecha()),l.getIva10(),l.getIva5(),l.getTipo(),l.getId_fac().getId_fac(),null,l.getId_fac().getTimbrado()
                                 }); 
                            }   
                        }
                        
                    }
                }
            }  
             
        }
    }
    
    private void mostrarlibros(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tablibros();
        libroivam.setModal(true);
        libroivam.setLocation(x,y);
        libroivam.setLocationRelativeTo(null);
        libroivam.setVisible(true);
    } 
}
